"""The demo catalogue.

Each entry drives both the text vector (name/description/brand/attributes) and the
generated product image (category shape + colour), so text-to-text and image-to-image
similarity both have real structure to find. Edit freely — the seeder re-reads this.
"""

from typing import TypedDict


class CatalogEntry(TypedDict):
    sku: str
    name: str
    description: str
    category: str
    brand: str
    price: float
    color: str
    attributes: dict[str, str]


CATALOG: list[CatalogEntry] = [
    # --- sneakers -------------------------------------------------------------
    {
        "sku": "SNK-001",
        "name": "Trailblazer Running Sneaker",
        "description": "Lightweight breathable mesh running shoe with a cushioned foam midsole for long road miles.",
        "category": "sneakers",
        "brand": "Kinetix",
        "price": 129.00,
        "color": "crimson",
        "attributes": {"use": "running", "material": "mesh"},
    },
    {
        "sku": "SNK-002",
        "name": "Court Classic Leather Sneaker",
        "description": "Retro low-top tennis silhouette in full-grain white leather with a gum rubber outsole.",
        "category": "sneakers",
        "brand": "Meridian",
        "price": 95.00,
        "color": "ivory",
        "attributes": {"use": "casual", "material": "leather"},
    },
    {
        "sku": "SNK-003",
        "name": "Summit Trail Runner",
        "description": "Aggressive lugged trail shoe with a rock plate and water-resistant upper for muddy terrain.",
        "category": "sneakers",
        "brand": "Kinetix",
        "price": 149.00,
        "color": "forest",
        "attributes": {"use": "trail", "material": "synthetic"},
    },
    {
        "sku": "SNK-004",
        "name": "Neon Street Trainer",
        "description": "Chunky street-style trainer with a bold neon accent and thick cushioned sole.",
        "category": "sneakers",
        "brand": "Volta",
        "price": 110.00,
        "color": "electric",
        "attributes": {"use": "casual", "material": "knit"},
    },
    # --- jackets --------------------------------------------------------------
    {
        "sku": "JKT-001",
        "name": "Alpine Down Puffer Jacket",
        "description": "Insulated 700-fill down puffer with a storm hood, built for sub-zero winter mornings.",
        "category": "jackets",
        "brand": "Northvale",
        "price": 289.00,
        "color": "midnight",
        "attributes": {"season": "winter", "material": "nylon"},
    },
    {
        "sku": "JKT-002",
        "name": "Harbour Rain Shell",
        "description": "Fully seam-sealed waterproof rain shell that packs down into its own chest pocket.",
        "category": "jackets",
        "brand": "Northvale",
        "price": 175.00,
        "color": "ocean",
        "attributes": {"season": "spring", "material": "ripstop"},
    },
    {
        "sku": "JKT-003",
        "name": "Heritage Waxed Cotton Jacket",
        "description": "Waxed cotton field jacket with a corduroy collar and four bellowed utility pockets.",
        "category": "jackets",
        "brand": "Ashcroft",
        "price": 320.00,
        "color": "olive",
        "attributes": {"season": "autumn", "material": "waxed cotton"},
    },
    {
        "sku": "JKT-004",
        "name": "Featherlight Windbreaker",
        "description": "Ultralight packable windbreaker in translucent ripstop with elasticated cuffs.",
        "category": "jackets",
        "brand": "Volta",
        "price": 89.00,
        "color": "sunrise",
        "attributes": {"season": "summer", "material": "ripstop"},
    },
    # --- watches --------------------------------------------------------------
    {
        "sku": "WCH-001",
        "name": "Meridian Automatic Dive Watch",
        "description": "Stainless steel automatic dive watch rated to 300m with a ceramic rotating bezel.",
        "category": "watches",
        "brand": "Meridian",
        "price": 649.00,
        "color": "ocean",
        "attributes": {"movement": "automatic", "material": "steel"},
    },
    {
        "sku": "WCH-002",
        "name": "Minimalist Field Watch",
        "description": "Slim 38mm field watch with a matte sand dial, leather strap and quiet quartz movement.",
        "category": "watches",
        "brand": "Ashcroft",
        "price": 210.00,
        "color": "sand",
        "attributes": {"movement": "quartz", "material": "leather"},
    },
    {
        "sku": "WCH-003",
        "name": "Pulse Smart Fitness Watch",
        "description": "Touchscreen fitness smartwatch tracking heart rate, sleep and GPS routes for seven days.",
        "category": "watches",
        "brand": "Volta",
        "price": 299.00,
        "color": "midnight",
        "attributes": {"movement": "digital", "material": "silicone"},
    },
    {
        "sku": "WCH-004",
        "name": "Rose Gold Dress Watch",
        "description": "Polished rose gold dress watch with a mother-of-pearl face and mesh milanese bracelet.",
        "category": "watches",
        "brand": "Ashcroft",
        "price": 385.00,
        "color": "rosewood",
        "attributes": {"movement": "quartz", "material": "steel"},
    },
    # --- backpacks ------------------------------------------------------------
    {
        "sku": "BAG-001",
        "name": "Commuter Laptop Backpack",
        "description": "Water-resistant commuter backpack with a padded 16-inch laptop sleeve and luggage passthrough.",
        "category": "backpacks",
        "brand": "Ashcroft",
        "price": 145.00,
        "color": "midnight",
        "attributes": {"capacity": "22L", "material": "polyester"},
    },
    {
        "sku": "BAG-002",
        "name": "Summit 45 Hiking Pack",
        "description": "Ventilated 45-litre hiking pack with an aluminium frame and hip belt for multi-day treks.",
        "category": "backpacks",
        "brand": "Northvale",
        "price": 230.00,
        "color": "forest",
        "attributes": {"capacity": "45L", "material": "nylon"},
    },
    {
        "sku": "BAG-003",
        "name": "Canvas Roll-Top Daypack",
        "description": "Waxed canvas roll-top daypack with leather straps and a brass hardware closure.",
        "category": "backpacks",
        "brand": "Ashcroft",
        "price": 165.00,
        "color": "sand",
        "attributes": {"capacity": "18L", "material": "canvas"},
    },
    {
        "sku": "BAG-004",
        "name": "Neon Sport Sling",
        "description": "Compact single-strap sling bag in bright neon ripstop for cycling and gym runs.",
        "category": "backpacks",
        "brand": "Volta",
        "price": 68.00,
        "color": "electric",
        "attributes": {"capacity": "8L", "material": "ripstop"},
    },
    # --- headphones -----------------------------------------------------------
    {
        "sku": "AUD-001",
        "name": "Studio Over-Ear Headphones",
        "description": "Closed-back over-ear studio headphones with memory foam pads and a detachable cable.",
        "category": "headphones",
        "brand": "Volta",
        "price": 199.00,
        "color": "midnight",
        "attributes": {"type": "over-ear", "noise_cancelling": "no"},
    },
    {
        "sku": "AUD-002",
        "name": "Silent Commute ANC Headphones",
        "description": "Active noise cancelling wireless headphones with 40 hours of battery and a travel case.",
        "category": "headphones",
        "brand": "Kinetix",
        "price": 349.00,
        "color": "ivory",
        "attributes": {"type": "over-ear", "noise_cancelling": "yes"},
    },
    {
        "sku": "AUD-003",
        "name": "Crimson Sport Earbuds",
        "description": "Sweatproof wireless sport earbuds with fin tips that stay put through hard intervals.",
        "category": "headphones",
        "brand": "Kinetix",
        "price": 129.00,
        "color": "crimson",
        "attributes": {"type": "in-ear", "noise_cancelling": "no"},
    },
    # --- lamps ----------------------------------------------------------------
    {
        "sku": "LMP-001",
        "name": "Arc Brass Floor Lamp",
        "description": "Sweeping arc floor lamp with a brushed brass stem and a marble weighted base.",
        "category": "lamps",
        "brand": "Halden",
        "price": 420.00,
        "color": "sand",
        "attributes": {"style": "mid-century", "material": "brass"},
    },
    {
        "sku": "LMP-002",
        "name": "Paper Globe Table Lamp",
        "description": "Soft rice-paper globe table lamp that throws a warm diffuse glow across a room.",
        "category": "lamps",
        "brand": "Halden",
        "price": 95.00,
        "color": "ivory",
        "attributes": {"style": "japandi", "material": "paper"},
    },
    {
        "sku": "LMP-003",
        "name": "Industrial Task Lamp",
        "description": "Adjustable articulated task lamp in matte black steel with a weighted clamp base.",
        "category": "lamps",
        "brand": "Halden",
        "price": 130.00,
        "color": "midnight",
        "attributes": {"style": "industrial", "material": "steel"},
    },
    # --- chairs ---------------------------------------------------------------
    {
        "sku": "CHR-001",
        "name": "Walnut Lounge Chair",
        "description": "Mid-century lounge chair with a bent walnut frame and tufted leather cushions.",
        "category": "chairs",
        "brand": "Halden",
        "price": 890.00,
        "color": "rosewood",
        "attributes": {"style": "mid-century", "material": "walnut"},
    },
    {
        "sku": "CHR-002",
        "name": "Mesh Ergonomic Desk Chair",
        "description": "Breathable mesh office chair with adjustable lumbar support and a synchro-tilt mechanism.",
        "category": "chairs",
        "brand": "Volta",
        "price": 460.00,
        "color": "midnight",
        "attributes": {"style": "ergonomic", "material": "mesh"},
    },
    {
        "sku": "CHR-003",
        "name": "Olive Velvet Accent Chair",
        "description": "Deep olive velvet accent chair with a curved back and tapered oak legs.",
        "category": "chairs",
        "brand": "Halden",
        "price": 540.00,
        "color": "olive",
        "attributes": {"style": "contemporary", "material": "velvet"},
    },
    # --- mugs -----------------------------------------------------------------
    {
        "sku": "MUG-001",
        "name": "Stoneware Pour-Over Mug",
        "description": "Hand-thrown speckled stoneware mug with a reactive glaze, holds 350ml of coffee.",
        "category": "mugs",
        "brand": "Halden",
        "price": 32.00,
        "color": "sand",
        "attributes": {"capacity": "350ml", "material": "stoneware"},
    },
    {
        "sku": "MUG-002",
        "name": "Vacuum Travel Tumbler",
        "description": "Double-walled vacuum travel tumbler that keeps coffee hot for six hours on the commute.",
        "category": "mugs",
        "brand": "Kinetix",
        "price": 38.00,
        "color": "ocean",
        "attributes": {"capacity": "450ml", "material": "steel"},
    },
    {
        "sku": "MUG-003",
        "name": "Crimson Enamel Camp Mug",
        "description": "Chip-resistant enamel camp mug with a rolled rim, built for campfires and cold mornings.",
        "category": "mugs",
        "brand": "Northvale",
        "price": 24.00,
        "color": "crimson",
        "attributes": {"capacity": "300ml", "material": "enamel"},
    },
]

#: Palette shared by the image generator so colour words match the rendered pixels.
COLORS: dict[str, tuple[int, int, int]] = {
    "crimson": (194, 47, 60),
    "ivory": (240, 236, 227),
    "forest": (44, 89, 62),
    "electric": (198, 232, 44),
    "midnight": (32, 38, 55),
    "ocean": (38, 106, 148),
    "olive": (108, 116, 62),
    "sunrise": (232, 145, 62),
    "sand": (206, 178, 133),
    "rosewood": (150, 90, 84),
}
